import os

BOT_TOKEN = os.getenv("BOT_TOKEN")

GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
GOOGLE_SHEETS_SPREADSHEET_ID = os.getenv(
    "GOOGLE_SHEETS_SPREADSHEET_ID",
    "1-z6YD8dtDMHJJESc4hEgNeWpkcwu0btD7c4kDy6qqEg",
)
GOOGLE_SHEETS_TAB_NAME = os.getenv("GOOGLE_SHEETS_TAB_NAME", "Транзакции")
